### ISSUE TITLE
Missing cuDNN in GPU example ?

### ISSUE THREAD

**Issue by jonathanBieler** [MurrellGroup/Jjama3.jl#12]
The GPU example the readme didn't work for me (windows machine) unless I added `using cuDNN` (seen in the doc of MLDataDevices) :

https://github.com/LuxDL/Lux.jl/blob/main/lib/MLDataDevices/src/public.jl#L122 (this is called by `gpu`).

**Comment by murrellb** [comment]
Thanks! I've added a note in the readme that this might be needed (it doesn't seem to be necessary on our systems but we've never tried Windows).
